package cz.cvut.fel.jankupat.AlkoApp.model.enums;

/**
 * @author Patrik Jankuv
 * @created 8/9/2020
 */
public enum AchievementEnum {
    BEGINNING_OF_CONTROL_OVER_DRINKING,
    COMPLIANCE_WITH_THE_PLAN,
    COMPLIANCE_WITH_PLAN_10_DAYS,
    COMPLIANCE_WITH_PLAN_100_DAYS,
    OVERCOMING_THE_PLAN,
    OVERCOME_PLAN_10_DAYS,
    OVERCOME_PLAN_100_DAYS,
    ONE_DAY_ABSTINENCE,
    WITHOUT_ALCOHOL_10_DAYS,
    WITHOUT_ALCOHOL_100_DAYS
}
